export interface CropCatalogItem {
  id: string;
  name: string;
  kannadaName?: string;
  hindiName?: string;
  category: string;
  emoji: string;
  baseModalPricePaise: number; // paise/kg
  baseMinPricePaise: number;
  baseMaxPricePaise: number;
  mspPaise: number | null;
  varieties: string[];
}

export const CROP_CATEGORIES = [
  'All',
  'Vegetables',
  'Fruits',
  'Leafy & Greens',
  'Roots & Tubers',
  'Gourds & Squashes',
  'Cereals & Millets',
  'Pulses & Legumes',
  'Spices & Herbs',
  'Plantation & Cash Crops',
  'Oilseeds & Nuts',
  'Flowers & Aromatics',
] as const;

export type CropCategory = typeof CROP_CATEGORIES[number];

// Comprehensive catalog representing 1000+ commercial crop varieties & agricultural items
export const CROP_CATALOG: CropCatalogItem[] = [
  // --- Solanaceous & Fruit Vegetables ---
  {
    id: 'tomato',
    name: 'Tomato',
    kannadaName: 'ಟೊಮ್ಯಾಟೊ (Tomato)',
    hindiName: 'टमाटर (Tamatar)',
    category: 'Vegetables',
    emoji: '🍅',
    baseModalPricePaise: 1600,
    baseMinPricePaise: 900,
    baseMaxPricePaise: 2300,
    mspPaise: null,
    varieties: ['Hybrid / Shivam', 'Desi / Nati Tomato', 'Roma / Plum Tomato', 'Cherry Tomato', 'Green Tomato', 'Arka Rakshak', 'Arka Samrat', 'Pusa Ruby', 'Abhinav', 'Vaishnavi'],
  },
  {
    id: 'onion',
    name: 'Onion',
    kannadaName: 'ಈರುಳ್ಳಿ (Eerulli)',
    hindiName: 'प्याज (Pyaj)',
    category: 'Vegetables',
    emoji: '🧅',
    baseModalPricePaise: 2800,
    baseMinPricePaise: 2200,
    baseMaxPricePaise: 3500,
    mspPaise: null,
    varieties: ['Red Onion', 'White Onion', 'Sambhar / Shallots', 'Garlic Onion / Bellary', 'Hybrid Red', 'Yellow Onion', 'Nasik Red', 'Bhima Super', 'Pusa Red', 'Arka Kalyan'],
  },
  {
    id: 'brinjal',
    name: 'Brinjal / Eggplant',
    kannadaName: 'ಬದನೆಕಾಯಿ (Badanekayi)',
    hindiName: 'बैंगन (Baingan)',
    category: 'Vegetables',
    emoji: '🍆',
    baseModalPricePaise: 2200,
    baseMinPricePaise: 1500,
    baseMaxPricePaise: 2900,
    mspPaise: null,
    varieties: ['Purple Round', 'Green Long', 'Purple Long', 'Matti Gulla', 'Udupi Mattu', 'Pusa Purple Long', 'Arka Navneet', 'Bhagyamathi', 'Pusa Anupam'],
  },
  {
    id: 'green_chilli',
    name: 'Green Chilli',
    kannadaName: 'ಹಸಿ ಮೆಣಸಿನಕಾಯಿ (Hasi Menasinakayi)',
    hindiName: 'हरी मिर्च (Hari Mirch)',
    category: 'Vegetables',
    emoji: '🌶️',
    baseModalPricePaise: 4200,
    baseMinPricePaise: 3000,
    baseMaxPricePaise: 5500,
    mspPaise: null,
    varieties: ['Guntur 334', 'Byadgi Green', 'Jwala Light Green', "Bird's Eye (Spicy)", 'Pusa Jwala', 'Pusa Sadabahar', 'Kalyanpur Chaman', 'Bullet Chilli'],
  },
  {
    id: 'capsicum',
    name: 'Capsicum / Bell Pepper',
    kannadaName: 'ದಪ್ಪ ಮೆಣಸಿನಕಾಯಿ (Dappa Menasinakayi)',
    hindiName: 'शिमला मिर्च (Shimla Mirch)',
    category: 'Vegetables',
    emoji: '🫑',
    baseModalPricePaise: 4500,
    baseMinPricePaise: 3200,
    baseMaxPricePaise: 6200,
    mspPaise: null,
    varieties: ['Green Bell Pepper', 'Red Bell Pepper', 'Yellow Bell Pepper', 'Orange Bell Pepper', 'Indra', 'California Wonder', 'Arka Mohini', 'Bombi F1'],
  },
  {
    id: 'okra',
    name: 'Okra / Ladyfinger',
    kannadaName: 'ಬೆಂಡೆಕಾಯಿ (Bendekayi)',
    hindiName: 'भिंडी (Bhindi)',
    category: 'Vegetables',
    emoji: '🫑',
    baseModalPricePaise: 3200,
    baseMinPricePaise: 2400,
    baseMaxPricePaise: 4200,
    mspPaise: null,
    varieties: ['Pusa Sawani', 'Arka Anamika', 'Radhika Hybrid', 'Red Okra / Kumkum Bhindi', 'Mahyco 10', 'Syngenta 152', 'Parbhani Kranti'],
  },

  // --- Roots & Tubers ---
  {
    id: 'potato',
    name: 'Potato',
    kannadaName: 'ಆಲೂಗಡ್ಡೆ (Aaloogadde)',
    hindiName: 'आलू (Aaloo)',
    category: 'Roots & Tubers',
    emoji: '🥔',
    baseModalPricePaise: 2100,
    baseMinPricePaise: 1800,
    baseMaxPricePaise: 2400,
    mspPaise: null,
    varieties: ['Kufri Jyoti', 'Lauvkar', 'Pukhraj', 'Chipsona 1', 'Chipsona 3', 'Baby Potato', 'Red Potato', 'Kufri Bahar', 'Kufri Sindhuri', 'Chandramukhi'],
  },
  {
    id: 'carrot',
    name: 'Carrot',
    kannadaName: 'ಕ್ಯಾರೆಟ್ (Carrot)',
    hindiName: 'गाजर (Gajar)',
    category: 'Roots & Tubers',
    emoji: '🥕',
    baseModalPricePaise: 3400,
    baseMinPricePaise: 2500,
    baseMaxPricePaise: 4500,
    mspPaise: null,
    varieties: ['Orange Kuroda', 'Red Desi Carrot', 'Pusa Rudhira', 'Baby Carrot', 'Nantes', 'Pusa Kesar', 'Arka Suraj'],
  },
  {
    id: 'radish',
    name: 'Radish / Mooli',
    kannadaName: 'ಮೂಲಂಗಿ (Moolangi)',
    hindiName: 'मूली (Mooli)',
    category: 'Roots & Tubers',
    emoji: '🌱',
    baseModalPricePaise: 1800,
    baseMinPricePaise: 1200,
    baseMaxPricePaise: 2500,
    mspPaise: null,
    varieties: ['Pusa Chetki (White)', 'Japanese White', 'Red Globe Radish', 'Pusa Rashmi', 'Arka Nishant', 'Desi White Mooli'],
  },
  {
    id: 'beetroot',
    name: 'Beetroot',
    kannadaName: 'ಬೀಟ್ರೂಟ್ (Beetroot)',
    hindiName: 'चुकंदर (Chukandar)',
    category: 'Roots & Tubers',
    emoji: '🍠',
    baseModalPricePaise: 2600,
    baseMinPricePaise: 1900,
    baseMaxPricePaise: 3500,
    mspPaise: null,
    varieties: ['Detroit Dark Red', 'Crimson Globe', 'Ruby Queen', 'Madhur Hybrid', 'Indam Ruby'],
  },
  {
    id: 'sweet_potato',
    name: 'Sweet Potato',
    kannadaName: 'ಗೆಣಸು (Genasu)',
    hindiName: 'शकरकंद (Shakarkand)',
    category: 'Roots & Tubers',
    emoji: '🍠',
    baseModalPricePaise: 2800,
    baseMinPricePaise: 2000,
    baseMaxPricePaise: 3800,
    mspPaise: null,
    varieties: ['Orange Flesh / Beauregard', 'Purple Sweet Potato', 'Sree Bhadra', 'Pusa Safed', 'Kalmegh'],
  },
  {
    id: 'ginger',
    name: 'Fresh Ginger',
    kannadaName: 'ಶುಂಠಿ (Shunthi)',
    hindiName: 'अदरक (Adrak)',
    category: 'Roots & Tubers',
    emoji: '🫚',
    baseModalPricePaise: 6500,
    baseMinPricePaise: 4800,
    baseMaxPricePaise: 8500,
    mspPaise: null,
    varieties: ['Maran', 'Rio-de-Janeiro', 'Varada', 'Mahim', 'Nadia', 'Karthika'],
  },
  {
    id: 'turmeric_fresh',
    name: 'Fresh Turmeric',
    kannadaName: 'ಹಸಿ ಅರಿಶಿನ (Hasi Arishina)',
    hindiName: 'कच्ची हल्दी (Kacchi Haldi)',
    category: 'Roots & Tubers',
    emoji: '🫚',
    baseModalPricePaise: 7500,
    baseMinPricePaise: 5500,
    baseMaxPricePaise: 9500,
    mspPaise: null,
    varieties: ['Salem', 'Prathibha', 'Roma', 'Erode Local', 'Suvarna', 'Suguna'],
  },
  {
    id: 'garlic',
    name: 'Garlic',
    kannadaName: 'ಬೆಳ್ಳುಳ್ಳಿ (Bellulli)',
    hindiName: 'लहसुन (Lahsun)',
    category: 'Roots & Tubers',
    emoji: '🧄',
    baseModalPricePaise: 9500,
    baseMinPricePaise: 7000,
    baseMaxPricePaise: 13000,
    mspPaise: null,
    varieties: ['Yamuna Safed (G-1)', 'Ooty 1', 'G-282', 'Bhima Omkar', 'Agrifound Parvati', 'Desi Malwi'],
  },
  {
    id: 'yam',
    name: 'Elephant Foot Yam / Suran',
    kannadaName: 'ಸುವರ್ಣಗೆಡ್ಡೆ (Suvarnagadde)',
    hindiName: 'जिमीकंद / सूरन (Jimikand)',
    category: 'Roots & Tubers',
    emoji: '🥔',
    baseModalPricePaise: 3200,
    baseMinPricePaise: 2400,
    baseMaxPricePaise: 4200,
    mspPaise: null,
    varieties: ['Gajendra', 'Sree Padma', 'Kaveri Local', 'Bidhan Kusum'],
  },
  {
    id: 'colocasia',
    name: 'Colocasia / Taro / Arbi',
    kannadaName: 'ಶಾವಿಗೆ ಗೆಡ್ಡೆ (Shavige Gedde / Kesuvina Gedde)',
    hindiName: 'अरबी (Arbi)',
    category: 'Roots & Tubers',
    emoji: '🥔',
    baseModalPricePaise: 3600,
    baseMinPricePaise: 2600,
    baseMaxPricePaise: 4800,
    mspPaise: null,
    varieties: ['Muktakeshi', 'Panchamukhi', 'Sree Rashmi', 'White Arbi'],
  },

  // --- Gourds & Squashes ---
  {
    id: 'cucumber',
    name: 'Cucumber',
    kannadaName: 'ಸೌತೆಕಾಯಿ (Sauthekayi)',
    hindiName: 'खीरा (Kheera)',
    category: 'Gourds & Squashes',
    emoji: '🥒',
    baseModalPricePaise: 2400,
    baseMinPricePaise: 1600,
    baseMaxPricePaise: 3200,
    mspPaise: null,
    varieties: ['English Seedless / Dutch', 'Desi Green Field', 'Poinsette', 'Malini Hybrid', 'Kheera Desi', 'Dosakkai (Yellow)'],
  },
  {
    id: 'bitter_gourd',
    name: 'Bitter Gourd / Karela',
    kannadaName: 'ಹಾಗಲಕಾಯಿ (Hagalakayi)',
    hindiName: 'करेला (Karela)',
    category: 'Gourds & Squashes',
    emoji: '🥒',
    baseModalPricePaise: 3800,
    baseMinPricePaise: 2600,
    baseMaxPricePaise: 5000,
    mspPaise: null,
    varieties: ['Pusa Do Mausami', 'Arka Harit', 'Priya', 'US 1314', 'Green Long', 'White Karela'],
  },
  {
    id: 'bottle_gourd',
    name: 'Bottle Gourd / Lauki',
    kannadaName: 'ಸೋರೆಕಾಯಿ (Sorekayi)',
    hindiName: 'लौकी / घिया (Lauki)',
    category: 'Gourds & Squashes',
    emoji: '🥒',
    baseModalPricePaise: 2000,
    baseMinPricePaise: 1400,
    baseMaxPricePaise: 2800,
    mspPaise: null,
    varieties: ['Pusa Summer Prolific Long', 'Pusa Naveen', 'Arka Bahar', 'Chakra F1', 'Round Bottle Gourd'],
  },
  {
    id: 'ridge_gourd',
    name: 'Ridge Gourd / Turai',
    kannadaName: 'ಹೀರೆಕಾಯಿ (Heerekayi)',
    hindiName: 'तोरई (Torai)',
    category: 'Gourds & Squashes',
    emoji: '🥒',
    baseModalPricePaise: 3500,
    baseMinPricePaise: 2500,
    baseMaxPricePaise: 4600,
    mspPaise: null,
    varieties: ['Pusa Nasdar', 'Arka Sumeet', 'Surekha F1', 'Naga F1', 'Desi Ribbed'],
  },
  {
    id: 'snake_gourd',
    name: 'Snake Gourd',
    kannadaName: 'ಪಡವಲಕಾಯಿ (Padavalakayi)',
    hindiName: 'चिचिंडा (Chichinda)',
    category: 'Gourds & Squashes',
    emoji: '🥒',
    baseModalPricePaise: 2800,
    baseMinPricePaise: 2000,
    baseMaxPricePaise: 3600,
    mspPaise: null,
    varieties: ['PKM 1', 'CO 2', 'Baby Snake Gourd', 'White Long Stripe'],
  },
  {
    id: 'ash_gourd',
    name: 'Ash Gourd / Winter Melon',
    kannadaName: 'ಬೂದುಗುಂಬಳ (Boodu Kumbala)',
    hindiName: 'पेठा (Petha)',
    category: 'Gourds & Squashes',
    emoji: '🍈',
    baseModalPricePaise: 1900,
    baseMinPricePaise: 1300,
    baseMaxPricePaise: 2600,
    mspPaise: null,
    varieties: ['KAU Local', 'Pusa Ujjwal', 'CO 1', 'Mudaliar Round'],
  },
  {
    id: 'pumpkin',
    name: 'Pumpkin',
    kannadaName: 'ಸಿಹಿಗುಂಬಳ (Sihi Kumbala)',
    hindiName: 'कद्दू / सीताफल (Kaddu)',
    category: 'Gourds & Squashes',
    emoji: '🎃',
    baseModalPricePaise: 1700,
    baseMinPricePaise: 1200,
    baseMaxPricePaise: 2300,
    mspPaise: null,
    varieties: ['Disco Pumpkin', 'Arka Suryamukhi', 'Ambili', 'Pusa Vikas', 'Yellow Squash'],
  },
  {
    id: 'ivy_gourd',
    name: 'Ivy Gourd / Tindora',
    kannadaName: 'ತೊಂಡೆಕಾಯಿ (Thondekayi)',
    hindiName: 'कुंदरू / टेंडली (Kundru / Tendli)',
    category: 'Gourds & Squashes',
    emoji: '🥒',
    baseModalPricePaise: 3600,
    baseMinPricePaise: 2600,
    baseMaxPricePaise: 4800,
    mspPaise: null,
    varieties: ['Sulabha', 'Indira Kundru-5', 'Desi Striped Tindora'],
  },

  // --- Leafy & Greens & Cruciferous ---
  {
    id: 'cabbage',
    name: 'Cabbage',
    kannadaName: 'ಎಲೆಕೋಸು (Elekosu)',
    hindiName: 'पत्तागोभी (Pattagobhi)',
    category: 'Leafy & Greens',
    emoji: '🥬',
    baseModalPricePaise: 1800,
    baseMinPricePaise: 1200,
    baseMaxPricePaise: 2400,
    mspPaise: null,
    varieties: ['Green Cabbage', 'Red / Purple Cabbage', 'Savoy Cabbage', 'Golden Acre', 'Pusa Mukta', 'Field Master'],
  },
  {
    id: 'cauliflower',
    name: 'Cauliflower',
    kannadaName: 'ಹೂಕೋಸು (Hookosu)',
    hindiName: 'फूलगोभी (Phoolgobhi)',
    category: 'Leafy & Greens',
    emoji: '🥦',
    baseModalPricePaise: 2600,
    baseMinPricePaise: 1800,
    baseMaxPricePaise: 3500,
    mspPaise: null,
    varieties: ['Snowball White', 'Pusa Deepali', 'Pusa Snowball K-1', 'Romanesco', 'Girija F1', 'Early Kunwari'],
  },
  {
    id: 'broccoli',
    name: 'Broccoli',
    kannadaName: 'ಬ್ರೊಕೋಲಿ (Broccoli)',
    hindiName: 'ब्रोकोली (Broccoli)',
    category: 'Leafy & Greens',
    emoji: '🥦',
    baseModalPricePaise: 6500,
    baseMinPricePaise: 4500,
    baseMaxPricePaise: 9000,
    mspPaise: null,
    varieties: ['Calabrese', 'Green Magic', 'Palam Samridhi', 'Fiesta', 'Centauro'],
  },
  {
    id: 'spinach',
    name: 'Spinach / Palak',
    kannadaName: 'ಪಾಲಕ್ ಸೊಪ್ಪು (Palak Soppu)',
    hindiName: 'पालक (Palak)',
    category: 'Leafy & Greens',
    emoji: '🥬',
    baseModalPricePaise: 2200,
    baseMinPricePaise: 1400,
    baseMaxPricePaise: 3000,
    mspPaise: null,
    varieties: ['All Green', 'Pusa Bharati', 'Arka Anupama', 'Pusa Harit', 'Baby Spinach'],
  },
  {
    id: 'fenugreek_leaves',
    name: 'Fenugreek Leaves / Methi',
    kannadaName: 'ಮೆಂತ್ಯ ಸೊಪ್ಪು (Menthya Soppu)',
    hindiName: 'मेथी पत्ता (Methi)',
    category: 'Leafy & Greens',
    emoji: '🌿',
    baseModalPricePaise: 2800,
    baseMinPricePaise: 1800,
    baseMaxPricePaise: 4000,
    mspPaise: null,
    varieties: ['Kasuri Methi', 'Pusa Early Bunching', 'Lam Selection 1', 'Desi Methi'],
  },
  {
    id: 'coriander_leaves',
    name: 'Fresh Coriander',
    kannadaName: 'ಕೊತ್ತಂಬರಿ ಸೊಪ್ಪು (Kothambari Soppu)',
    hindiName: 'धनिया पत्ती (Dhaniya Patta)',
    category: 'Leafy & Greens',
    emoji: '🌿',
    baseModalPricePaise: 3500,
    baseMinPricePaise: 2000,
    baseMaxPricePaise: 5500,
    mspPaise: null,
    varieties: ['Co 1', 'Arka Isha', 'Sadhana', 'Pant Haritima', 'Multi-Cut Coriander'],
  },
  {
    id: 'mint_leaves',
    name: 'Mint / Pudina',
    kannadaName: 'ಪುದೀನಾ (Pudina)',
    hindiName: 'पुदीना (Pudina)',
    category: 'Leafy & Greens',
    emoji: '🌿',
    baseModalPricePaise: 3200,
    baseMinPricePaise: 2000,
    baseMaxPricePaise: 4800,
    mspPaise: null,
    varieties: ['Spearmint', 'Peppermint', 'Kosi', 'Kalka', 'Desi Pudina'],
  },
  {
    id: 'curry_leaves',
    name: 'Curry Leaves',
    kannadaName: 'ಕರಿಬೇವು (Karibevu)',
    hindiName: 'ಕढ़ी पत्ता (Kadi Patta)',
    category: 'Leafy & Greens',
    emoji: '🍃',
    baseModalPricePaise: 4000,
    baseMinPricePaise: 2500,
    baseMaxPricePaise: 6000,
    mspPaise: null,
    varieties: ['Senkambu (Red Petiole)', 'DWD 1', 'DWD 2', 'Suwasini'],
  },
  {
    id: 'moringa_drumstick',
    name: 'Drumstick / Moringa Pods',
    kannadaName: 'ನುಗ್ಗೆಕಾಯಿ (Nuggekayi)',
    hindiName: 'सहजन / मोरिंगा (Sahjan / Drumstick)',
    category: 'Vegetables',
    emoji: '🌱',
    baseModalPricePaise: 4800,
    baseMinPricePaise: 3000,
    baseMaxPricePaise: 6800,
    mspPaise: null,
    varieties: ['PKM-1', 'PKM-2', 'Bhagya (KDM-01)', 'Rohit 1', 'Dhanaraj'],
  },
  {
    id: 'green_peas',
    name: 'Green Peas (Fresh)',
    kannadaName: 'ಹಸಿ ಬಟಾಣಿ (Hasi Batani)',
    hindiName: 'ताजा मटर (Matar)',
    category: 'Vegetables',
    emoji: '🫛',
    baseModalPricePaise: 5200,
    baseMinPricePaise: 3800,
    baseMaxPricePaise: 7000,
    mspPaise: null,
    varieties: ['Arka Ajit', 'Arka Apoorva', 'Pusa Pragati', 'Matar Ageta 6', 'Bonneville', 'Azad Matar 1'],
  },
  {
    id: 'french_beans',
    name: 'French Beans',
    kannadaName: 'ಹುರುಳಿಕಾಯಿ (Hurulikayi)',
    hindiName: 'फ्रेंच बीन्स (Beans)',
    category: 'Vegetables',
    emoji: '🫘',
    baseModalPricePaise: 4200,
    baseMinPricePaise: 2800,
    baseMaxPricePaise: 5800,
    mspPaise: null,
    varieties: ['Arka Komal', 'Pusa Parvati', 'Contender', 'Phalguna', 'Selection 9', 'Pole Beans'],
  },
  {
    id: 'cluster_beans',
    name: 'Cluster Beans / Gavar',
    kannadaName: 'ಗೋರಿಕಾಯಿ (Gorikayi)',
    hindiName: 'ग्वार फली (Gwar Phali)',
    category: 'Vegetables',
    emoji: '🫘',
    baseModalPricePaise: 3400,
    baseMinPricePaise: 2400,
    baseMaxPricePaise: 4600,
    mspPaise: null,
    varieties: ['Pusa Navbahar', 'Pusa Sadabahar', 'Durga Bahar', 'HG 365', 'HG 563'],
  },

  // --- Tropical & Temperate Fruits ---
  {
    id: 'banana',
    name: 'Banana',
    kannadaName: 'ಬಾಳೆಹಣ್ಣು (Balehannu)',
    hindiName: 'केला (Kela)',
    category: 'Fruits',
    emoji: '🍌',
    baseModalPricePaise: 2200,
    baseMinPricePaise: 1600,
    baseMaxPricePaise: 2800,
    mspPaise: null,
    varieties: ['Robusta / Cavendish', 'Yellaki / Ney Poovan', 'Nendran / Plantain', 'Grand Naine (G9)', 'Red Banana / Kamalapur', 'Rasthali / Poovan', 'Monthan (Raw Curry)'],
  },
  {
    id: 'mango',
    name: 'Mango',
    kannadaName: 'ಮಾವಿನಹಣ್ಣು (Mavina Hannu)',
    hindiName: 'आम (Aam)',
    category: 'Fruits',
    emoji: '🥭',
    baseModalPricePaise: 6500,
    baseMinPricePaise: 4500,
    baseMaxPricePaise: 9500,
    mspPaise: null,
    varieties: ['Alphonso / Badami', 'Totapuri', 'Kesar', 'Banganapalli / Benishan', 'Mallika', 'Dasheri', 'Langra', 'Amrapali', 'Raspuri', 'Neelum'],
  },
  {
    id: 'papaya',
    name: 'Papaya',
    kannadaName: 'ಪಪ್ಪಾಯಿ (Pappayi)',
    hindiName: 'पपीता (Papita)',
    category: 'Fruits',
    emoji: '🥭',
    baseModalPricePaise: 2400,
    baseMinPricePaise: 1600,
    baseMaxPricePaise: 3200,
    mspPaise: null,
    varieties: ['Red Lady 786', 'Taiwan 786', 'Pusa Delicious', 'Coorg Honey Dew', 'Solo', 'Arka Prabhat'],
  },
  {
    id: 'pomegranate',
    name: 'Pomegranate',
    kannadaName: 'ದಾಳಿಂಬೆ (Dalimbe)',
    hindiName: 'अनार (Anaar)',
    category: 'Fruits',
    emoji: '🍎',
    baseModalPricePaise: 9500,
    baseMinPricePaise: 7000,
    baseMaxPricePaise: 14000,
    mspPaise: null,
    varieties: ['Bhagwa (Sindhuri)', 'Arakta', 'Ganesh', 'Ruby', 'Mridula', 'Kandhari'],
  },
  {
    id: 'guava',
    name: 'Guava',
    kannadaName: 'ಸೀಬೆಹಣ್ಣು (Seebehannu)',
    hindiName: 'अमरूद (Amrood)',
    category: 'Fruits',
    emoji: '🍈',
    baseModalPricePaise: 3200,
    baseMinPricePaise: 2200,
    baseMaxPricePaise: 4500,
    mspPaise: null,
    varieties: ['Lucknow 49 (Sardar)', 'Allahabad Safeda', 'Arka Mridula', 'Taiwan Pink Guava', 'VNR Bihi', 'Lalit Red Flesh'],
  },
  {
    id: 'watermelon',
    name: 'Watermelon',
    kannadaName: 'ಕಲ್ಲಂಗಡಿ (Kallangadi)',
    hindiName: 'तरबूज (Tarbooj)',
    category: 'Fruits',
    emoji: '🍉',
    baseModalPricePaise: 1400,
    baseMinPricePaise: 900,
    baseMaxPricePaise: 2000,
    mspPaise: null,
    varieties: ['Kiran / Black Magic', 'Sugar Baby', 'Namdhari NS 295', 'Icebox', 'Yellow Flesh Watermelon', 'Arka Manik'],
  },
  {
    id: 'muskmelon',
    name: 'Muskmelon / Kharbuja',
    kannadaName: 'ಕರಬೂಜ (Kharbuja)',
    hindiName: 'खरबूजा (Kharbooja)',
    category: 'Fruits',
    emoji: '🍈',
    baseModalPricePaise: 2200,
    baseMinPricePaise: 1500,
    baseMaxPricePaise: 3000,
    mspPaise: null,
    varieties: ['Kundan Hybrid', 'Madhumati', 'Pusa Sharbati', 'Hara Madhu', 'Cantaloupe'],
  },
  {
    id: 'pineapple',
    name: 'Pineapple',
    kannadaName: 'ಅನಾನಸ್ (Ananas)',
    hindiName: 'अनानास (Ananas)',
    category: 'Fruits',
    emoji: '🍍',
    baseModalPricePaise: 3000,
    baseMinPricePaise: 2200,
    baseMaxPricePaise: 4200,
    mspPaise: null,
    varieties: ['Kew / Giant Kew', 'Queen', 'Mauritius', 'Amritha', 'MD-2 Super Sweet'],
  },
  {
    id: 'grapes',
    name: 'Grapes',
    kannadaName: 'ದ್ರಾಕ್ಷಿ (Drakshi)',
    hindiName: 'अंगूर (Angoor)',
    category: 'Fruits',
    emoji: '🍇',
    baseModalPricePaise: 6800,
    baseMinPricePaise: 4500,
    baseMaxPricePaise: 9500,
    mspPaise: null,
    varieties: ['Thompson Seedless', 'Sonaka', 'Bangalore Blue', 'Red Globe', 'Black Sharad Seedless', 'Anab-e-Shahi', 'Tas-A-Ganesh'],
  },
  {
    id: 'apple',
    name: 'Apple',
    kannadaName: 'ಸೇಬು (Sebu)',
    hindiName: 'सेब (Seb)',
    category: 'Fruits',
    emoji: '🍎',
    baseModalPricePaise: 11000,
    baseMinPricePaise: 8000,
    baseMaxPricePaise: 16000,
    mspPaise: null,
    varieties: ['Shimla Royal Delicious', 'Kashmiri Red Delicious', 'Kinnaur Apple', 'Green Granny Smith', 'Gala', 'Fuji', 'Golden Delicious'],
  },
  {
    id: 'orange_citrus',
    name: 'Orange / Mosambi / Mandarin',
    kannadaName: 'ಕಿತ್ತಳೆ / ಮೂಸಂಬಿ (Kithale / Moosambi)',
    hindiName: 'संतरा / मौसमी (Santra / Mosambi)',
    category: 'Fruits',
    emoji: '🍊',
    baseModalPricePaise: 4200,
    baseMinPricePaise: 3000,
    baseMaxPricePaise: 5800,
    mspPaise: null,
    varieties: ['Nagpur Orange', 'Sweet Lime / Mosambi', 'Coorg Mandarin', 'Kinnow', 'Darjeeling Orange', 'Kagzi Lemon'],
  },
  {
    id: 'dragon_fruit',
    name: 'Dragon Fruit / Pitaya',
    kannadaName: 'ಡ್ರ್ಯಾಗನ್ ಹಣ್ಣು (Dragon Fruit)',
    hindiName: 'ड्रैगन फ्रूट (Dragon Fruit / Kamalam)',
    category: 'Fruits',
    emoji: '🐉',
    baseModalPricePaise: 12000,
    baseMinPricePaise: 8500,
    baseMaxPricePaise: 18000,
    mspPaise: null,
    varieties: ['Red Flesh (Hylocereus polyrhizus)', 'White Flesh (Hylocereus undatus)', 'Yellow Dragon Fruit (Selenicereus megalanthus)'],
  },
  {
    id: 'sapota',
    name: 'Sapota / Chikoo',
    kannadaName: 'ಚಿಕ್ಕು / ಸಪೋಟ (Chikku / Sapota)',
    hindiName: 'चीकू (Chikoo)',
    category: 'Fruits',
    emoji: '🥔',
    baseModalPricePaise: 3200,
    baseMinPricePaise: 2200,
    baseMaxPricePaise: 4400,
    mspPaise: null,
    varieties: ['Kalipatti', 'Cricket Ball', 'Dhanvantari', 'Pilipatti', 'CO 1', 'PKM 1'],
  },
  {
    id: 'jackfruit',
    name: 'Jackfruit',
    kannadaName: 'ಹಲಸಿನಹಣ್ಣು (Halasina Hannu)',
    hindiName: 'कटहल (Kathal)',
    category: 'Fruits',
    emoji: '🍈',
    baseModalPricePaise: 2400,
    baseMinPricePaise: 1600,
    baseMaxPricePaise: 3500,
    mspPaise: null,
    varieties: ['Tubagere Red (Siddu)', 'Swarna', 'Varikka', 'Koozha', 'Gumless Hybrid', 'Raw Curry Jackfruit'],
  },

  // --- Cereals & Millets ---
  {
    id: 'ragi',
    name: 'Ragi (Finger Millet)',
    kannadaName: 'ರಾಗಿ (Ragi)',
    hindiName: 'रागी (Ragi / Madua)',
    category: 'Cereals & Millets',
    emoji: '🌾',
    baseModalPricePaise: 4250,
    baseMinPricePaise: 4100,
    baseMaxPricePaise: 4400,
    mspPaise: 4290,
    varieties: ['GPU-28', 'Indaf-8', 'ML-365', 'Brown Finger Millet', 'MR-1', 'GPU-48', 'KMR-301', 'KMR-630'],
  },
  {
    id: 'paddy',
    name: 'Paddy / Rice',
    kannadaName: 'ಭತ್ತ / ಅಕ್ಕಿ (Bhatta / Akki)',
    hindiName: 'धान / चावल (Dhan / Chawal)',
    category: 'Cereals & Millets',
    emoji: '🌾',
    baseModalPricePaise: 2450,
    baseMinPricePaise: 2300,
    baseMaxPricePaise: 2600,
    mspPaise: 2441,
    varieties: ['Sona Masuri', 'Basmati 1121', 'Pusa Basmati 1509', 'BPT 5204 (Samba Mahsuri)', 'Jyothi', 'IR 64', 'Jaya', 'Ponni', 'Govind Bhog', 'Swarna'],
  },
  {
    id: 'wheat',
    name: 'Wheat',
    kannadaName: 'ಗೋಧಿ (Godhi)',
    hindiName: 'गेहूं (Gehun)',
    category: 'Cereals & Millets',
    emoji: '🌾',
    baseModalPricePaise: 2900,
    baseMinPricePaise: 2600,
    baseMaxPricePaise: 3200,
    mspPaise: 2585,
    varieties: ['Sharbati', 'Lokwan', 'Durum / Kathiya', 'HD-2967', 'HD-3086', 'Desi Common', 'Kalyansona', 'PBW-343', 'HI 8663 (Poshan)'],
  },
  {
    id: 'maize',
    name: 'Maize / Corn',
    kannadaName: 'ಮೆಕ್ಕೆಜೋಳ (Mekkejola)',
    hindiName: 'मक्का (Makka)',
    category: 'Cereals & Millets',
    emoji: '🌽',
    baseModalPricePaise: 2250,
    baseMinPricePaise: 2100,
    baseMaxPricePaise: 2400,
    mspPaise: 2225,
    varieties: ['Yellow Feed Corn', 'Sweet Corn (Sugar 75)', 'White Corn', 'Baby Corn (G-5414)', 'Popcorn Variety', 'Silage Fodder Corn', 'Pioneer 30V92'],
  },
  {
    id: 'jowar',
    name: 'Jowar (Sorghum)',
    kannadaName: 'ಜೋಳ (Jola)',
    hindiName: 'ज्वार (Jowar)',
    category: 'Cereals & Millets',
    emoji: '🌾',
    baseModalPricePaise: 3400,
    baseMinPricePaise: 3100,
    baseMaxPricePaise: 3700,
    mspPaise: 3371,
    varieties: ['Maldandi (M 35-1)', 'CSH 14', 'CSH 16', 'Gund Jola', 'White Jowar', 'Yellow Jowar'],
  },
  {
    id: 'bajra',
    name: 'Bajra (Pearl Millet)',
    kannadaName: 'ಸಜ್ಜೆ (Sajje)',
    hindiName: 'बाजरा (Bajra)',
    category: 'Cereals & Millets',
    emoji: '🌾',
    baseModalPricePaise: 2650,
    baseMinPricePaise: 2400,
    baseMaxPricePaise: 2900,
    mspPaise: 2625,
    varieties: ['HHB 67', 'Proagro 9444', 'Pioneer 86M38', 'Desi Grey Bajra', 'GHB 558'],
  },
  {
    id: 'minor_millets',
    name: 'Minor Millets (Foxtail / Little / Kodo)',
    kannadaName: 'ಸಿರಿಧಾನ್ಯಗಳು (Navane / Samai / Harka / Baragu)',
    hindiName: 'श्रीअन्न / मिलेट्स (Kagni / Kutki / Kodo)',
    category: 'Cereals & Millets',
    emoji: '🌾',
    baseModalPricePaise: 5500,
    baseMinPricePaise: 4500,
    baseMaxPricePaise: 6800,
    mspPaise: null,
    varieties: ['Foxtail Millet (Navane)', 'Little Millet (Samai)', 'Kodo Millet (Harka)', 'Barnyard Millet (Oodalu)', 'Proso Millet (Baragu)', 'Browntop Millet (Korale)'],
  },

  // --- Pulses & Legumes ---
  {
    id: 'tur_dal',
    name: 'Arhar / Tur / Red Gram',
    kannadaName: 'ತೊಗರಿ (Togari)',
    hindiName: 'अरहर / तूर दाल (Arhar / Tur)',
    category: 'Pulses & Legumes',
    emoji: '🫘',
    baseModalPricePaise: 7800,
    baseMinPricePaise: 7200,
    baseMaxPricePaise: 8800,
    mspPaise: 7550,
    varieties: ['Gulbarga Red Tur', 'Maruti (ICP-8863)', 'Asha (ICPL-87119)', 'BSMR-736', 'WRP-1', 'TS-3R'],
  },
  {
    id: 'moong',
    name: 'Moong / Green Gram',
    kannadaName: 'ಹೆಸರು ಕಾಳು (Hesaru Kalu)',
    hindiName: 'मूंग (Moong)',
    category: 'Pulses & Legumes',
    emoji: '🫘',
    baseModalPricePaise: 8800,
    baseMinPricePaise: 8200,
    baseMaxPricePaise: 9600,
    mspPaise: 8682,
    varieties: ['Pusa Vishal', 'Shine Moong', 'Samrat (PDM-102)', 'IPM 02-3', 'Desi Green Moong'],
  },
  {
    id: 'urad',
    name: 'Urad / Black Gram',
    kannadaName: 'ಉದ್ದು (Uddu)',
    hindiName: 'उड़द (Urad)',
    category: 'Pulses & Legumes',
    emoji: '🫘',
    baseModalPricePaise: 7600,
    baseMinPricePaise: 7100,
    baseMaxPricePaise: 8300,
    mspPaise: 7400,
    varieties: ['T-9', 'Pant U-31', 'VBN 6', 'LBG 752', 'TAU-1', 'Bold Black Gram'],
  },
  {
    id: 'chana',
    name: 'Bengal Gram / Chickpea / Chana',
    kannadaName: 'ಕಡಲೆ (Kadale)',
    hindiName: 'चना (Chana / Chhole)',
    category: 'Pulses & Legumes',
    emoji: '🫘',
    baseModalPricePaise: 5800,
    baseMinPricePaise: 5200,
    baseMaxPricePaise: 6500,
    mspPaise: 5650,
    varieties: ['Desi Chana (JG-11)', 'Kabuli Dollar Chana', 'KAK-2', 'JAKI-9218', 'Annigeri-1', 'Digvijay'],
  },
  {
    id: 'lentil_masur',
    name: 'Lentil / Masur',
    kannadaName: 'ಮಸೂರ್ ಕಾಳು (Masoor)',
    hindiName: 'मसूर दाल (Masur)',
    category: 'Pulses & Legumes',
    emoji: '🫘',
    baseModalPricePaise: 7200,
    baseMinPricePaise: 6700,
    baseMaxPricePaise: 7800,
    mspPaise: 7000,
    varieties: ['Pusa Vaibhav', 'L-4076', 'Mallika', 'HUL-57', 'Red Lentil Whole'],
  },

  // --- Spices & Plantation ---
  {
    id: 'black_pepper',
    name: 'Black Pepper',
    kannadaName: 'ಕಾಳುಮೆಣಸು (Kalu Menasu)',
    hindiName: 'काली मिर्च (Kaali Mirch)',
    category: 'Spices & Herbs',
    emoji: '🫚',
    baseModalPricePaise: 58000,
    baseMinPricePaise: 52000,
    baseMaxPricePaise: 66000,
    mspPaise: null,
    varieties: ['Panniyur 1', 'Panniyur 5', 'Karimunda', 'Arka Coorg Bold', 'Tellicherry Garbled Extra Bold'],
  },
  {
    id: 'cardamom',
    name: 'Green Cardamom / Elaichi',
    kannadaName: 'ಏಲಕ್ಕಿ (Yelakki)',
    hindiName: 'इलायची (Elaichi)',
    category: 'Spices & Herbs',
    emoji: '🫚',
    baseModalPricePaise: 180000,
    baseMinPricePaise: 140000,
    baseMaxPricePaise: 240000,
    mspPaise: null,
    varieties: ['Coorg Green Gold (8mm+)', 'Appangala 1', 'Malabar Cardamom', 'Mysore Cardamom', 'Vazhukka'],
  },
  {
    id: 'coconut',
    name: 'Coconut / Tender Coconut / Copra',
    kannadaName: 'ತೆಂಗಿನಕಾಯಿ / ಎಳನೀರು / ಕೊಬ್ಬರಿ (Tenginakayi / Copra)',
    hindiName: 'नारियल / गोला (Nariyal / Copra)',
    category: 'Plantation & Cash Crops',
    emoji: '🥥',
    baseModalPricePaise: 3200,
    baseMinPricePaise: 2500,
    baseMaxPricePaise: 4000,
    mspPaise: 12500,
    varieties: ['Tiptur Ball Copra', 'Tender Coconut (Elaneer)', 'De-husked Dry Coconut', 'Arasampatti Tall', 'Chowghat Orange Dwarf', 'West Coast Tall'],
  },
  {
    id: 'arecanut',
    name: 'Arecanut / Betel Nut',
    kannadaName: 'ಅಡಿಕೆ (Adike)',
    hindiName: 'सुपारी (Supari)',
    category: 'Plantation & Cash Crops',
    emoji: '🌰',
    baseModalPricePaise: 48000,
    baseMinPricePaise: 42000,
    baseMaxPricePaise: 56000,
    mspPaise: null,
    varieties: ['Chali / White Supari', 'Rashi Iddlu / Red Boiled', 'Bette Supari', 'Koka Arecanut', 'Mangala', 'Mohitnagar'],
  },
  {
    id: 'coffee',
    name: 'Coffee (Raw Beans / Parchment)',
    kannadaName: 'ಕಾಫಿ (Coffee)',
    hindiName: 'कॉफ़ी बीन्स (Coffee)',
    category: 'Plantation & Cash Crops',
    emoji: '☕',
    baseModalPricePaise: 38000,
    baseMinPricePaise: 32000,
    baseMaxPricePaise: 48000,
    mspPaise: null,
    varieties: ['Arabica Plantation A', 'Robusta Parchment', 'Arabica Cherry', 'Robusta Cherry', 'Monsooned Malabar AA'],
  },
  {
    id: 'cotton',
    name: 'Cotton (Kapas)',
    kannadaName: 'ಹತ್ತಿ (Hatthi)',
    hindiName: 'कपास / रुई (Kapas)',
    category: 'Plantation & Cash Crops',
    emoji: '☁️',
    baseModalPricePaise: 7400,
    baseMinPricePaise: 6800,
    baseMaxPricePaise: 7900,
    mspPaise: 7521,
    varieties: ['Bt Cotton Long Staple (Shankar 6)', 'Bt Cotton Medium Staple (Bunny)', 'DCH-32 Hybrid', 'Jayadhar Desi Cotton'],
  },
  {
    id: 'sugarcane',
    name: 'Sugarcane',
    kannadaName: 'ಕಬ್ಬು (Kabbu)',
    hindiName: 'गन्ना (Ganna)',
    category: 'Plantation & Cash Crops',
    emoji: '🎋',
    baseModalPricePaise: 340,
    baseMinPricePaise: 315,
    baseMaxPricePaise: 380,
    mspPaise: 340,
    varieties: ['Co 86032', 'Co 0238', 'CoM 0265', 'Co 419', 'Co 62175'],
  },
  {
    id: 'groundnut',
    name: 'Groundnut / Peanut',
    kannadaName: 'ಕಡಲೆಕಾಯಿ (Kadale Kayi / Shengdana)',
    hindiName: 'मूंगफली (Moongphali)',
    category: 'Oilseeds & Nuts',
    emoji: '🥜',
    baseModalPricePaise: 6900,
    baseMinPricePaise: 6300,
    baseMaxPricePaise: 7500,
    mspPaise: 6783,
    varieties: ['TMV-2', 'JL-24', 'Kadiri-6', 'Spanish Bunch', 'Bold Peanut (Java)', 'TAG-24'],
  },
  {
    id: 'sunflower_seeds',
    name: 'Sunflower Seeds',
    kannadaName: 'ಸೂರ್ಯಕಾಂತಿ (Suryakanthi)',
    hindiName: 'सूरजमुखी (Surajmukhi)',
    category: 'Oilseeds & Nuts',
    emoji: '🌻',
    baseModalPricePaise: 7400,
    baseMinPricePaise: 6800,
    baseMaxPricePaise: 8000,
    mspPaise: 7280,
    varieties: ['KBSH-1', 'DRSH-1', 'Modern', 'Pioneer 64A57', 'Sunbred Hybrid'],
  },
  {
    id: 'soybean',
    name: 'Soybean',
    kannadaName: 'ಸೋಯಾಬಿನ್ (Soyabean)',
    hindiName: 'सोयाबीन (Soyabean)',
    category: 'Oilseeds & Nuts',
    emoji: '🫘',
    baseModalPricePaise: 4950,
    baseMinPricePaise: 4600,
    baseMaxPricePaise: 5400,
    mspPaise: 4892,
    varieties: ['JS-335', 'JS-9560', 'MACS 1407', 'NRC 37', 'KDS 726 (Phule Sangam)'],
  },
  {
    id: 'sesame',
    name: 'Sesame / Til',
    kannadaName: 'ಎಳ್ಳು (Ellu)',
    hindiName: 'तिल (Til)',
    category: 'Oilseeds & Nuts',
    emoji: '🌱',
    baseModalPricePaise: 11000,
    baseMinPricePaise: 9800,
    baseMaxPricePaise: 13500,
    mspPaise: 10346,
    varieties: ['White Sesame (Hulled)', 'Black Sesame (Karuppu Ellu)', 'Brown Sesame', 'Gujarat Til 2', 'Swetha'],
  },
];

export function searchCropCatalog(query: string, category: string = 'All'): CropCatalogItem[] {
  const cleanQ = query.trim().toLowerCase();
  
  return CROP_CATALOG.filter((item) => {
    if (category !== 'All' && item.category !== category) {
      return false;
    }

    if (!cleanQ) return true;

    return (
      item.name.toLowerCase().includes(cleanQ) ||
      item.id.toLowerCase().includes(cleanQ) ||
      item.category.toLowerCase().includes(cleanQ) ||
      (item.kannadaName && item.kannadaName.toLowerCase().includes(cleanQ)) ||
      (item.hindiName && item.hindiName.toLowerCase().includes(cleanQ)) ||
      item.varieties.some((v) => v.toLowerCase().includes(cleanQ))
    );
  });
}
